services:
  api:
    build: ./backend
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/requirements.txt:/app/requirements.txt:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 3s
      retries: 5

  web:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    environment:
      # desde el front (navegador) se accede por localhost:5173,
      # pero las requests al backend dentro de la red docker van a http://api:8000
      VITE_API_URL: "http://api:8000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
