services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 3s
      retries: 5

  web:
    build:
      context: ./frontend
      args:
        # el front llamará al backend por el hostname del servicio en la red de docker
        VITE_API_URL: "http://api:8000"
    ports:
      - "8080:80"
    depends_on:
      - api
